name: flutter_cheez
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.1+12

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:



  flutter:
    sdk: flutter

  #Flutter cash
  cached_network_image: ^2.3.2
  sprintf: ^5.0.0
  webview_flutter: ^0.3.24
  flutter_svg: ^0.19.0
  cupertino_icons: ^1.0.0
  event_bus: ^1.1.1
  yandex_mapkit: ^0.4.0
  location: ^3.0.2
  tuple: ^1.0.3
  intl: ^0.16.1
  geocoder: ^0.2.1
  autocomplete_textfield: ^1.7.3
  http: ^0.12.2
  flutter_masked_text: ^0.8.0
  shared_preferences: ^0.5.12
  flutter_launcher_icons: ^0.8.0
  html: ^0.14.0+3
  dotted_border: ^1.0.6
  firebase_messaging: ^7.0.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.4

dev_dependencies:

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/assets/backgrounds/empty_history.png
    - lib/assets/backgrounds/empty_cart.png
    - lib/assets/backgrounds/splash_screen.png
    - lib/assets/backgrounds/drawer.png
    - lib/assets/backgrounds/discount.svg
    - lib/assets/images/logo.png
    - lib/assets/images/animated_logo.gif
    - lib/assets/icons/cheese.svg
    - lib/assets/icons/round-information-button.svg
    - lib/assets/icons/shopping-bag.svg
    - lib/assets/icons/shopping-basket.svg
    - lib/assets/icons/check_box.png
    - lib/assets/icons/map_pointer_shop.png
    - lib/assets/icons/map_pointer_home.png
    - lib/assets/icons/order_call.svg
    - lib/assets/icons/order_delivery.svg
    - lib/assets/icons/order_done.svg
    - lib/assets/icons/order_pay.svg
    - lib/assets/icons/info_pay.svg
    - lib/assets/icons/info_user.svg
    - lib/assets/icons/info_time.svg
    - lib/assets/icons/info_adres.svg
    - lib/assets/icons/info_delivery.svg
    - lib/assets/icons/toggle_off.svg
    - lib/assets/icons/toggle_on.svg
    - lib/assets/icons/address.png
    - lib/assets/icons/arrow_right.svg
    - lib/assets/icons/arrow_left.svg
    - lib/assets/icons/show_pass.svg


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


